// =====================================================================
// /blog — Public blog index, editorial-voice essays.
// Auto-generated by the engine, attributed to LaunchVault Editorial.
// =====================================================================

import { createFileRoute, Link } from "@tanstack/react-router";
import { Sparkles, ArrowRight, Clock, type LucideIcon } from "lucide-react";
import { PublicLayout } from "@/components/landing/PublicLayout";
import { listPublicLibrary } from "@/utils/public-content.functions";
import { buildSeoMeta, buildSeoLinks, jsonLdScript, breadcrumbJsonLd } from "@/lib/seo";
import { brand } from "@/config/brand";

export const Route = createFileRoute("/blog/")({
  loader: async () => {
    const items = await listPublicLibrary({ data: { type: "essay", limit: 60 } });
    return { items };
  },
  head: () => ({
    meta: buildSeoMeta({
      title: "Learn AI — Guides & Essays on Using AI | LaunchVault Blog",
      description: "Practical essays and guides on how to learn AI and use it for real work — prompting, AI agents, automation, and building with AI. Editorial-voice writing from the LaunchVault AI learning platform.",
      path: "/blog",
    }),
    links: buildSeoLinks("/blog"),
    scripts: [
      jsonLdScript(breadcrumbJsonLd([
        { name: "Home", path: "/" },
        { name: "Blog", path: "/blog" },
      ])),
    ],
  }),
  component: BlogIndexPage,
});

function BlogIndexPage() {
  const { items } = Route.useLoaderData();

  return (
    <PublicLayout>
      {/* Hero */}
      <section className="relative isolate overflow-hidden border-b border-border bg-slate-950">
        <div aria-hidden className="pointer-events-none absolute inset-0">
          <div className="absolute -top-32 -left-16 h-[420px] w-[420px] rounded-full bg-amber-600/25 blur-[120px]" />
          <div className="absolute -bottom-32 -right-16 h-[420px] w-[420px] rounded-full bg-fuchsia-600/25 blur-[120px]" />
        </div>
        <div className="relative mx-auto max-w-5xl px-4 py-20 text-center text-white md:py-24">
          <span className="inline-flex items-center gap-1.5 rounded-full border border-amber-400/30 bg-amber-500/10 px-3 py-1 text-[11px] font-bold uppercase tracking-[0.18em] text-amber-200">
            <Sparkles className="h-3 w-3" /> Founder's notebook
          </span>
          <h1 className="font-display mt-6 text-balance text-5xl font-bold leading-[1.05] tracking-[-0.02em] md:text-[4rem]">
            Notes from
            <span className="block bg-gradient-to-r from-amber-300 via-orange-300 to-fuchsia-300 bg-clip-text text-transparent">
              the engine room.
            </span>
          </h1>
          <p className="mx-auto mt-5 max-w-2xl text-base leading-relaxed text-slate-300 md:text-lg">
            Essays by {brand.founder.name} on building autonomous content engines, prompting philosophy, indie SaaS economics, and what actually works in AI.
          </p>
        </div>
      </section>

      {/* Posts list */}
      <section className="mx-auto max-w-3xl px-4 py-16">
        {items.length === 0 ? (
          <EmptyState />
        ) : (
          <div className="space-y-10">
            {items.map((it: any) => <BlogCard key={it.id} item={it} />)}
          </div>
        )}
      </section>
    </PublicLayout>
  );
}

function BlogCard({ item }: { item: any }) {
  const date = new Date(item.created_at);
  const formatted = date.toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });

  return (
    <Link
      to="/blog/$slug"
      params={{ slug: item.slug ?? item.id }}
      className="group block border-b border-border pb-10 last:border-b-0"
    >
      <p className="flex items-center gap-3 text-[10.5px] font-bold uppercase tracking-[0.22em] text-muted-foreground">
        <span>{formatted}</span>
        {item.estimated_minutes && (
          <>
            <span className="h-px w-6 bg-border" />
            <span className="inline-flex items-center gap-1"><Clock className="h-3 w-3" /> {item.estimated_minutes} min</span>
          </>
        )}
      </p>
      <h2 className="font-display mt-3 text-balance text-[2rem] font-bold leading-[1.1] tracking-[-0.015em] text-foreground transition-colors group-hover:text-primary md:text-[2.5rem]">
        {item.title}
      </h2>
      {item.short_description && (
        <p className="font-display mt-4 max-w-[58ch] text-[1.15rem] italic leading-snug text-muted-foreground md:text-[1.25rem]">
          {item.short_description}
        </p>
      )}
      <p className="mt-5 inline-flex items-center gap-1.5 text-[12px] font-bold uppercase tracking-[0.18em] text-primary opacity-70 transition-opacity group-hover:opacity-100">
        Read essay <ArrowRight className="h-3.5 w-3.5 transition-transform group-hover:translate-x-0.5" />
      </p>
    </Link>
  );
}

function EmptyState() {
  return (
    <div className="rounded-3xl border border-dashed border-border bg-card p-12 text-center shadow-soft">
      <Sparkles className="mx-auto h-6 w-6 text-muted-foreground" />
      <p className="font-display mt-3 text-2xl font-bold">First essays drop soon</p>
      <p className="mt-2 text-sm text-muted-foreground">The engine publishes a new essay roughly every cycle.</p>
    </div>
  );
}

const _ = null as unknown as LucideIcon;
void _;
