import { createFileRoute, Link } from "@tanstack/react-router";
import { LegalPage } from "@/components/legal/LegalPage";
import { brand } from "@/config/brand";
import { buildSeoMeta, buildSeoLinks } from "@/lib/seo";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: buildSeoMeta({
      title: `Terms of Service — ${brand.brandName}`,
      description: `The terms governing your use of ${brand.brandName} — accounts, subscriptions, content licensing, AI-generated content, and intellectual property. Plain English.`,
      path: "/terms",
    }),
    links: buildSeoLinks("/terms"),
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      subtitle={`The contract between you and ${brand.brandName}. Plain English, real protections.`}
      lastUpdated="May 24, 2026"
      intro={
        <p>
          These Terms of Service (&ldquo;Terms&rdquo;) govern your access to and use of {brand.brandName}
          (the &ldquo;Service&rdquo;), operated by {brand.brandName} (&ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;). By creating an
          account or using the Service you agree to these Terms, our{" "}
          <Link to="/privacy" className="text-indigo-600 underline-offset-2 hover:underline">Privacy Policy</Link>,
          and our{" "}
          <Link to="/acceptable-use" className="text-indigo-600 underline-offset-2 hover:underline">Acceptable Use Policy</Link>.
          If you do not agree, do not use the Service.
        </p>
      }
      sections={[
        {
          id: "service",
          title: "What the Service is",
          body: (
            <>
              <p>{brand.brandName} is a self-growing AI mastery platform. It publishes ten types of educational content — AI prompts, micro-courses, workflows, agent blueprints, business lessons, daily insights, tool guides, playbooks, challenges, and cheatsheets — across 50 AI mastery domains.</p>
              <p>New content is generated, validated, and quality-scored by our autonomous backend (powered by large language models) and published on a recurring schedule. We disclose the AI-generated nature of the content openly. See &ldquo;AI-generated content&rdquo; below.</p>
            </>
          ),
        },
        {
          id: "eligibility",
          title: "Eligibility & accounts",
          body: (
            <>
              <p>You must be at least 16 years old and able to enter a binding contract. You are responsible for keeping your login credentials secure and for all activity on your account.</p>
              <p>You must provide accurate registration information and keep it current. We may suspend or terminate accounts that violate these Terms or that we reasonably suspect are fraudulent.</p>
            </>
          ),
        },
        {
          id: "subscriptions",
          title: "Subscriptions & billing",
          body: (
            <>
              <p>Subscriptions are billed monthly in advance through Stripe. Current plans: <strong className="text-foreground">Free</strong> ($0), <strong className="text-foreground">Starter</strong> ({brand.pricing.tier1.priceLabel}/mo), <strong className="text-foreground">Creator</strong> ({brand.pricing.tier2.priceLabel}/mo), <strong className="text-foreground">Pro</strong> ({brand.pricing.tier3.priceLabel}/mo). Higher tiers include all content from lower tiers.</p>
              <p>Your plan renews automatically until you cancel from your account page or the Stripe billing portal. Cancellations take effect at the end of the current billing period; you keep access until then.</p>
              <p>Taxes (VAT/GST/sales tax) may be applied based on your billing country and are calculated at checkout by Stripe.</p>
              <p>All charges are final and non-refundable. See our <Link to="/refund-policy" className="text-indigo-600 underline-offset-2 hover:underline">Cancellation Policy</Link> for full details — but the short version: we do not issue refunds, and you can cancel any time to stop future billing.</p>
            </>
          ),
        },
        {
          id: "ai-content",
          title: "AI-generated content (disclosure)",
          body: (
            <>
              <p>Most published content on {brand.brandName} — prompts, courses, workflows, agent blueprints, business lessons, insights, tool guides, playbooks, challenges, cheatsheets — is generated by large language models on a recurring schedule and quality-scored before publication.</p>
              <p>AI output may contain inaccuracies, outdated references, or simplifications. You are responsible for evaluating the content before applying it in your own work — particularly for medical, legal, financial, regulatory, or safety-critical contexts.</p>
              <p>We continuously refine our content prompts, validation, and scoring to maintain a high quality bar, but we make no warranty that any specific item is error-free. If you spot a factual error, please email <a href={`mailto:${brand.supportEmail}`} className="text-indigo-600 underline-offset-2 hover:underline">{brand.supportEmail}</a>.</p>
            </>
          ),
        },
        {
          id: "license",
          title: "Your license to the content",
          body: (
            <>
              <p>Content you unlock through your subscription tier is licensed to you under a perpetual, worldwide, non-exclusive, non-transferable license to use the content in your own personal or commercial projects (including using copy-ready prompts with third-party AI tools, applying workflows in your business, and adapting frameworks to your own materials).</p>
              <p>You <strong className="text-foreground">may not</strong>: (a) resell, sublicense, or redistribute substantial portions of the {brand.brandName} library as a competing product or library; (b) train, fine-tune, or evaluate competing AI models or competing prompt/learning libraries on our content; (c) scrape, mirror, or republish content at scale; (d) remove proprietary notices, branding, or attribution.</p>
              <p>The {brand.brandName} brand, name, logos, domain, design, software, and the underlying content-generation system remain our property.</p>
            </>
          ),
        },
        {
          id: "user-conduct",
          title: "Acceptable use",
          body: (
            <>
              <p>You agree not to misuse the Service, including: attempting to gain unauthorized access, interfering with other users, uploading malware, abusing the rate-limited APIs, or using the Service for unlawful, harmful, deceptive, or abusive purposes. See our{" "}
                <Link to="/acceptable-use" className="text-indigo-600 underline-offset-2 hover:underline">Acceptable Use Policy</Link> for the full list.</p>
            </>
          ),
        },
        {
          id: "third-party",
          title: "Third-party services",
          body: (
            <>
              <p>The Service relies on third parties. By using {brand.brandName} you also accept their terms when your data passes through them:</p>
              <ul className="mt-2 list-disc space-y-1.5 pl-5">
                <li><strong className="text-foreground">Stripe</strong> — payments and the subscription billing portal.</li>
                <li><strong className="text-foreground">Supabase</strong> — database, authentication, and Realtime updates.</li>
                <li><strong className="text-foreground">OpenAI</strong> — generative model inference used by our autonomous content engine (server-side only; we do not send your personal data to OpenAI in the normal course of content generation).</li>
                <li><strong className="text-foreground">Cloudflare</strong> — DNS, edge hosting, and Workers runtime.</li>
              </ul>
            </>
          ),
        },
        {
          id: "termination",
          title: "Termination",
          body: (
            <p>You may cancel your subscription at any time. We may suspend or terminate access if you breach these Terms or our Acceptable Use Policy. Upon termination, your license to previously-unlocked content survives, but access to ongoing subscription-only features ends.</p>
          ),
        },
        {
          id: "disclaimers",
          title: "Disclaimers & limitation of liability",
          body: (
            <>
              <p>The Service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties of any kind, express or implied, to the maximum extent permitted by law.</p>
              <p>AI-generated outputs may contain inaccuracies. You are responsible for reviewing any output before applying it. {brand.brandName} is not a substitute for professional medical, legal, financial, or other licensed advice.</p>
              <p>To the maximum extent permitted by law, {brand.brandName}&rsquo;s total liability arising out of or related to the Service is limited to the amount you paid us in the 12 months preceding the claim. We are not liable for indirect, incidental, or consequential damages.</p>
            </>
          ),
        },
        {
          id: "changes",
          title: "Changes to these Terms",
          body: (
            <p>We may update these Terms from time to time. Material changes will be notified by email or in-app at least 14 days in advance. Continued use after the effective date constitutes acceptance. The current version always lives at this URL; archived versions are available on request.</p>
          ),
        },
        {
          id: "law",
          title: "Governing law",
          body: (
            <p>These Terms are governed by the laws of the Province of Ontario, Canada (where {brand.brandName} is established), without regard to conflict-of-laws principles. Disputes will be resolved in the competent courts of Ontario.</p>
          ),
        },
        {
          id: "contact",
          title: "Contact",
          body: (
            <p>For questions about these Terms, email <a href={`mailto:${brand.supportEmail}`} className="text-indigo-600 underline-offset-2 hover:underline">{brand.supportEmail}</a> or use our <Link to="/contact" className="text-indigo-600 underline-offset-2 hover:underline">contact form</Link>.</p>
          ),
        },
      ]}
    />
  );
}
