/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearnAiRouteImport } from './routes/learn-ai'
import { Route as HowToLearnAiRouteImport } from './routes/how-to-learn-ai'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DpaRouteImport } from './routes/dpa'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AcceptableUseRouteImport } from './routes/acceptable-use'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as GlossaryIndexRouteImport } from './routes/glossary.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as LibrarySlugRouteImport } from './routes/library.$slug'
import { Route as GlossarySlugRouteImport } from './routes/glossary.$slug'
import { Route as DomainsSlugRouteImport } from './routes/domains.$slug'
import { Route as DashboardWorkflowsRouteImport } from './routes/dashboard.workflows'
import { Route as DashboardToolsRouteImport } from './routes/dashboard.tools'
import { Route as DashboardSavedRouteImport } from './routes/dashboard.saved'
import { Route as DashboardPromptsRouteImport } from './routes/dashboard.prompts'
import { Route as DashboardPlaybooksRouteImport } from './routes/dashboard.playbooks'
import { Route as DashboardLibraryRouteImport } from './routes/dashboard.library'
import { Route as DashboardInsightsRouteImport } from './routes/dashboard.insights'
import { Route as DashboardCoursesRouteImport } from './routes/dashboard.courses'
import { Route as DashboardCheatsheetsRouteImport } from './routes/dashboard.cheatsheets'
import { Route as DashboardChallengesRouteImport } from './routes/dashboard.challenges'
import { Route as DashboardBusinessRouteImport } from './routes/dashboard.business'
import { Route as DashboardAgentsRouteImport } from './routes/dashboard.agents'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardAccountRouteImport } from './routes/dashboard.account'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as DashboardContentIdRouteImport } from './routes/dashboard.content.$id'
import { Route as ApiPublicStatsRouteImport } from './routes/api/public/stats'
import { Route as ApiPublicSitemapRouteImport } from './routes/api/public/sitemap'
import { Route as ApiPublicRobotsRouteImport } from './routes/api/public/robots'
import { Route as ApiPublicLlmsRouteImport } from './routes/api/public/llms'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksTriggerCronRouteImport } from './routes/api/public/hooks/trigger-cron'
import { Route as ApiPublicHooksAutoGenerateContentRouteImport } from './routes/api/public/hooks/auto-generate-content'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnAiRoute = LearnAiRouteImport.update({
  id: '/learn-ai',
  path: '/learn-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToLearnAiRoute = HowToLearnAiRouteImport.update({
  id: '/how-to-learn-ai',
  path: '/how-to-learn-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DpaRoute = DpaRouteImport.update({
  id: '/dpa',
  path: '/dpa',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptableUseRoute = AcceptableUseRouteImport.update({
  id: '/acceptable-use',
  path: '/acceptable-use',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryIndexRoute = GlossaryIndexRouteImport.update({
  id: '/glossary/',
  path: '/glossary/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrarySlugRoute = LibrarySlugRouteImport.update({
  id: '/library/$slug',
  path: '/library/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossarySlugRoute = GlossarySlugRouteImport.update({
  id: '/glossary/$slug',
  path: '/glossary/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsSlugRoute = DomainsSlugRouteImport.update({
  id: '/domains/$slug',
  path: '/domains/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkflowsRoute = DashboardWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardToolsRoute = DashboardToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSavedRoute = DashboardSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPromptsRoute = DashboardPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlaybooksRoute = DashboardPlaybooksRouteImport.update({
  id: '/playbooks',
  path: '/playbooks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLibraryRoute = DashboardLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInsightsRoute = DashboardInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoursesRoute = DashboardCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCheatsheetsRoute = DashboardCheatsheetsRouteImport.update({
  id: '/cheatsheets',
  path: '/cheatsheets',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChallengesRoute = DashboardChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBusinessRoute = DashboardBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentsRoute = DashboardAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardContentIdRoute = DashboardContentIdRouteImport.update({
  id: '/content/$id',
  path: '/content/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicStatsRoute = ApiPublicStatsRouteImport.update({
  id: '/api/public/stats',
  path: '/api/public/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSitemapRoute = ApiPublicSitemapRouteImport.update({
  id: '/api/public/sitemap',
  path: '/api/public/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRobotsRoute = ApiPublicRobotsRouteImport.update({
  id: '/api/public/robots',
  path: '/api/public/robots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLlmsRoute = ApiPublicLlmsRouteImport.update({
  id: '/api/public/llms',
  path: '/api/public/llms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTriggerCronRoute =
  ApiPublicHooksTriggerCronRouteImport.update({
    id: '/api/public/hooks/trigger-cron',
    path: '/api/public/hooks/trigger-cron',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoGenerateContentRoute =
  ApiPublicHooksAutoGenerateContentRouteImport.update({
    id: '/api/public/hooks/auto-generate-content',
    path: '/api/public/hooks/auto-generate-content',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dpa': typeof DpaRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/how-to-learn-ai': typeof HowToLearnAiRoute
  '/learn-ai': typeof LearnAiRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/business': typeof DashboardBusinessRoute
  '/dashboard/challenges': typeof DashboardChallengesRoute
  '/dashboard/cheatsheets': typeof DashboardCheatsheetsRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/library': typeof DashboardLibraryRoute
  '/dashboard/playbooks': typeof DashboardPlaybooksRoute
  '/dashboard/prompts': typeof DashboardPromptsRoute
  '/dashboard/saved': typeof DashboardSavedRoute
  '/dashboard/tools': typeof DashboardToolsRoute
  '/dashboard/workflows': typeof DashboardWorkflowsRoute
  '/domains/$slug': typeof DomainsSlugRoute
  '/glossary/$slug': typeof GlossarySlugRoute
  '/library/$slug': typeof LibrarySlugRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/glossary/': typeof GlossaryIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/api/public/llms': typeof ApiPublicLlmsRoute
  '/api/public/robots': typeof ApiPublicRobotsRoute
  '/api/public/sitemap': typeof ApiPublicSitemapRoute
  '/api/public/stats': typeof ApiPublicStatsRoute
  '/dashboard/content/$id': typeof DashboardContentIdRoute
  '/api/public/hooks/auto-generate-content': typeof ApiPublicHooksAutoGenerateContentRoute
  '/api/public/hooks/trigger-cron': typeof ApiPublicHooksTriggerCronRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dpa': typeof DpaRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/how-to-learn-ai': typeof HowToLearnAiRoute
  '/learn-ai': typeof LearnAiRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/business': typeof DashboardBusinessRoute
  '/dashboard/challenges': typeof DashboardChallengesRoute
  '/dashboard/cheatsheets': typeof DashboardCheatsheetsRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/library': typeof DashboardLibraryRoute
  '/dashboard/playbooks': typeof DashboardPlaybooksRoute
  '/dashboard/prompts': typeof DashboardPromptsRoute
  '/dashboard/saved': typeof DashboardSavedRoute
  '/dashboard/tools': typeof DashboardToolsRoute
  '/dashboard/workflows': typeof DashboardWorkflowsRoute
  '/domains/$slug': typeof DomainsSlugRoute
  '/glossary/$slug': typeof GlossarySlugRoute
  '/library/$slug': typeof LibrarySlugRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/glossary': typeof GlossaryIndexRoute
  '/library': typeof LibraryIndexRoute
  '/api/public/llms': typeof ApiPublicLlmsRoute
  '/api/public/robots': typeof ApiPublicRobotsRoute
  '/api/public/sitemap': typeof ApiPublicSitemapRoute
  '/api/public/stats': typeof ApiPublicStatsRoute
  '/dashboard/content/$id': typeof DashboardContentIdRoute
  '/api/public/hooks/auto-generate-content': typeof ApiPublicHooksAutoGenerateContentRoute
  '/api/public/hooks/trigger-cron': typeof ApiPublicHooksTriggerCronRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dpa': typeof DpaRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/how-to-learn-ai': typeof HowToLearnAiRoute
  '/learn-ai': typeof LearnAiRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/business': typeof DashboardBusinessRoute
  '/dashboard/challenges': typeof DashboardChallengesRoute
  '/dashboard/cheatsheets': typeof DashboardCheatsheetsRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/library': typeof DashboardLibraryRoute
  '/dashboard/playbooks': typeof DashboardPlaybooksRoute
  '/dashboard/prompts': typeof DashboardPromptsRoute
  '/dashboard/saved': typeof DashboardSavedRoute
  '/dashboard/tools': typeof DashboardToolsRoute
  '/dashboard/workflows': typeof DashboardWorkflowsRoute
  '/domains/$slug': typeof DomainsSlugRoute
  '/glossary/$slug': typeof GlossarySlugRoute
  '/library/$slug': typeof LibrarySlugRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/glossary/': typeof GlossaryIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/api/public/llms': typeof ApiPublicLlmsRoute
  '/api/public/robots': typeof ApiPublicRobotsRoute
  '/api/public/sitemap': typeof ApiPublicSitemapRoute
  '/api/public/stats': typeof ApiPublicStatsRoute
  '/dashboard/content/$id': typeof DashboardContentIdRoute
  '/api/public/hooks/auto-generate-content': typeof ApiPublicHooksAutoGenerateContentRoute
  '/api/public/hooks/trigger-cron': typeof ApiPublicHooksTriggerCronRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/acceptable-use'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/dpa'
    | '/features'
    | '/how-it-works'
    | '/how-to-learn-ai'
    | '/learn-ai'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/signup'
    | '/terms'
    | '/blog/$slug'
    | '/checkout/return'
    | '/dashboard/account'
    | '/dashboard/admin'
    | '/dashboard/agents'
    | '/dashboard/business'
    | '/dashboard/challenges'
    | '/dashboard/cheatsheets'
    | '/dashboard/courses'
    | '/dashboard/insights'
    | '/dashboard/library'
    | '/dashboard/playbooks'
    | '/dashboard/prompts'
    | '/dashboard/saved'
    | '/dashboard/tools'
    | '/dashboard/workflows'
    | '/domains/$slug'
    | '/glossary/$slug'
    | '/library/$slug'
    | '/blog/'
    | '/dashboard/'
    | '/glossary/'
    | '/library/'
    | '/api/public/llms'
    | '/api/public/robots'
    | '/api/public/sitemap'
    | '/api/public/stats'
    | '/dashboard/content/$id'
    | '/api/public/hooks/auto-generate-content'
    | '/api/public/hooks/trigger-cron'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/acceptable-use'
    | '/contact'
    | '/cookies'
    | '/dpa'
    | '/features'
    | '/how-it-works'
    | '/how-to-learn-ai'
    | '/learn-ai'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/signup'
    | '/terms'
    | '/blog/$slug'
    | '/checkout/return'
    | '/dashboard/account'
    | '/dashboard/admin'
    | '/dashboard/agents'
    | '/dashboard/business'
    | '/dashboard/challenges'
    | '/dashboard/cheatsheets'
    | '/dashboard/courses'
    | '/dashboard/insights'
    | '/dashboard/library'
    | '/dashboard/playbooks'
    | '/dashboard/prompts'
    | '/dashboard/saved'
    | '/dashboard/tools'
    | '/dashboard/workflows'
    | '/domains/$slug'
    | '/glossary/$slug'
    | '/library/$slug'
    | '/blog'
    | '/dashboard'
    | '/glossary'
    | '/library'
    | '/api/public/llms'
    | '/api/public/robots'
    | '/api/public/sitemap'
    | '/api/public/stats'
    | '/dashboard/content/$id'
    | '/api/public/hooks/auto-generate-content'
    | '/api/public/hooks/trigger-cron'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/acceptable-use'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/dpa'
    | '/features'
    | '/how-it-works'
    | '/how-to-learn-ai'
    | '/learn-ai'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/signup'
    | '/terms'
    | '/blog/$slug'
    | '/checkout/return'
    | '/dashboard/account'
    | '/dashboard/admin'
    | '/dashboard/agents'
    | '/dashboard/business'
    | '/dashboard/challenges'
    | '/dashboard/cheatsheets'
    | '/dashboard/courses'
    | '/dashboard/insights'
    | '/dashboard/library'
    | '/dashboard/playbooks'
    | '/dashboard/prompts'
    | '/dashboard/saved'
    | '/dashboard/tools'
    | '/dashboard/workflows'
    | '/domains/$slug'
    | '/glossary/$slug'
    | '/library/$slug'
    | '/blog/'
    | '/dashboard/'
    | '/glossary/'
    | '/library/'
    | '/api/public/llms'
    | '/api/public/robots'
    | '/api/public/sitemap'
    | '/api/public/stats'
    | '/dashboard/content/$id'
    | '/api/public/hooks/auto-generate-content'
    | '/api/public/hooks/trigger-cron'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcceptableUseRoute: typeof AcceptableUseRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DpaRoute: typeof DpaRoute
  FeaturesRoute: typeof FeaturesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  HowToLearnAiRoute: typeof HowToLearnAiRoute
  LearnAiRoute: typeof LearnAiRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  DomainsSlugRoute: typeof DomainsSlugRoute
  GlossarySlugRoute: typeof GlossarySlugRoute
  LibrarySlugRoute: typeof LibrarySlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  GlossaryIndexRoute: typeof GlossaryIndexRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  ApiPublicLlmsRoute: typeof ApiPublicLlmsRoute
  ApiPublicRobotsRoute: typeof ApiPublicRobotsRoute
  ApiPublicSitemapRoute: typeof ApiPublicSitemapRoute
  ApiPublicStatsRoute: typeof ApiPublicStatsRoute
  ApiPublicHooksAutoGenerateContentRoute: typeof ApiPublicHooksAutoGenerateContentRoute
  ApiPublicHooksTriggerCronRoute: typeof ApiPublicHooksTriggerCronRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn-ai': {
      id: '/learn-ai'
      path: '/learn-ai'
      fullPath: '/learn-ai'
      preLoaderRoute: typeof LearnAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-learn-ai': {
      id: '/how-to-learn-ai'
      path: '/how-to-learn-ai'
      fullPath: '/how-to-learn-ai'
      preLoaderRoute: typeof HowToLearnAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpa': {
      id: '/dpa'
      path: '/dpa'
      fullPath: '/dpa'
      preLoaderRoute: typeof DpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceptable-use': {
      id: '/acceptable-use'
      path: '/acceptable-use'
      fullPath: '/acceptable-use'
      preLoaderRoute: typeof AcceptableUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary/': {
      id: '/glossary/'
      path: '/glossary'
      fullPath: '/glossary/'
      preLoaderRoute: typeof GlossaryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$slug': {
      id: '/library/$slug'
      path: '/library/$slug'
      fullPath: '/library/$slug'
      preLoaderRoute: typeof LibrarySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary/$slug': {
      id: '/glossary/$slug'
      path: '/glossary/$slug'
      fullPath: '/glossary/$slug'
      preLoaderRoute: typeof GlossarySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains/$slug': {
      id: '/domains/$slug'
      path: '/domains/$slug'
      fullPath: '/domains/$slug'
      preLoaderRoute: typeof DomainsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/workflows': {
      id: '/dashboard/workflows'
      path: '/workflows'
      fullPath: '/dashboard/workflows'
      preLoaderRoute: typeof DashboardWorkflowsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tools': {
      id: '/dashboard/tools'
      path: '/tools'
      fullPath: '/dashboard/tools'
      preLoaderRoute: typeof DashboardToolsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/saved': {
      id: '/dashboard/saved'
      path: '/saved'
      fullPath: '/dashboard/saved'
      preLoaderRoute: typeof DashboardSavedRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/prompts': {
      id: '/dashboard/prompts'
      path: '/prompts'
      fullPath: '/dashboard/prompts'
      preLoaderRoute: typeof DashboardPromptsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/playbooks': {
      id: '/dashboard/playbooks'
      path: '/playbooks'
      fullPath: '/dashboard/playbooks'
      preLoaderRoute: typeof DashboardPlaybooksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/library': {
      id: '/dashboard/library'
      path: '/library'
      fullPath: '/dashboard/library'
      preLoaderRoute: typeof DashboardLibraryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/insights': {
      id: '/dashboard/insights'
      path: '/insights'
      fullPath: '/dashboard/insights'
      preLoaderRoute: typeof DashboardInsightsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/courses': {
      id: '/dashboard/courses'
      path: '/courses'
      fullPath: '/dashboard/courses'
      preLoaderRoute: typeof DashboardCoursesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cheatsheets': {
      id: '/dashboard/cheatsheets'
      path: '/cheatsheets'
      fullPath: '/dashboard/cheatsheets'
      preLoaderRoute: typeof DashboardCheatsheetsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/challenges': {
      id: '/dashboard/challenges'
      path: '/challenges'
      fullPath: '/dashboard/challenges'
      preLoaderRoute: typeof DashboardChallengesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/business': {
      id: '/dashboard/business'
      path: '/business'
      fullPath: '/dashboard/business'
      preLoaderRoute: typeof DashboardBusinessRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agents': {
      id: '/dashboard/agents'
      path: '/agents'
      fullPath: '/dashboard/agents'
      preLoaderRoute: typeof DashboardAgentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/content/$id': {
      id: '/dashboard/content/$id'
      path: '/content/$id'
      fullPath: '/dashboard/content/$id'
      preLoaderRoute: typeof DashboardContentIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/stats': {
      id: '/api/public/stats'
      path: '/api/public/stats'
      fullPath: '/api/public/stats'
      preLoaderRoute: typeof ApiPublicStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sitemap': {
      id: '/api/public/sitemap'
      path: '/api/public/sitemap'
      fullPath: '/api/public/sitemap'
      preLoaderRoute: typeof ApiPublicSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/robots': {
      id: '/api/public/robots'
      path: '/api/public/robots'
      fullPath: '/api/public/robots'
      preLoaderRoute: typeof ApiPublicRobotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/llms': {
      id: '/api/public/llms'
      path: '/api/public/llms'
      fullPath: '/api/public/llms'
      preLoaderRoute: typeof ApiPublicLlmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/trigger-cron': {
      id: '/api/public/hooks/trigger-cron'
      path: '/api/public/hooks/trigger-cron'
      fullPath: '/api/public/hooks/trigger-cron'
      preLoaderRoute: typeof ApiPublicHooksTriggerCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-generate-content': {
      id: '/api/public/hooks/auto-generate-content'
      path: '/api/public/hooks/auto-generate-content'
      fullPath: '/api/public/hooks/auto-generate-content'
      preLoaderRoute: typeof ApiPublicHooksAutoGenerateContentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardAgentsRoute: typeof DashboardAgentsRoute
  DashboardBusinessRoute: typeof DashboardBusinessRoute
  DashboardChallengesRoute: typeof DashboardChallengesRoute
  DashboardCheatsheetsRoute: typeof DashboardCheatsheetsRoute
  DashboardCoursesRoute: typeof DashboardCoursesRoute
  DashboardInsightsRoute: typeof DashboardInsightsRoute
  DashboardLibraryRoute: typeof DashboardLibraryRoute
  DashboardPlaybooksRoute: typeof DashboardPlaybooksRoute
  DashboardPromptsRoute: typeof DashboardPromptsRoute
  DashboardSavedRoute: typeof DashboardSavedRoute
  DashboardToolsRoute: typeof DashboardToolsRoute
  DashboardWorkflowsRoute: typeof DashboardWorkflowsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardContentIdRoute: typeof DashboardContentIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardAgentsRoute: DashboardAgentsRoute,
  DashboardBusinessRoute: DashboardBusinessRoute,
  DashboardChallengesRoute: DashboardChallengesRoute,
  DashboardCheatsheetsRoute: DashboardCheatsheetsRoute,
  DashboardCoursesRoute: DashboardCoursesRoute,
  DashboardInsightsRoute: DashboardInsightsRoute,
  DashboardLibraryRoute: DashboardLibraryRoute,
  DashboardPlaybooksRoute: DashboardPlaybooksRoute,
  DashboardPromptsRoute: DashboardPromptsRoute,
  DashboardSavedRoute: DashboardSavedRoute,
  DashboardToolsRoute: DashboardToolsRoute,
  DashboardWorkflowsRoute: DashboardWorkflowsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardContentIdRoute: DashboardContentIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcceptableUseRoute: AcceptableUseRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DpaRoute: DpaRoute,
  FeaturesRoute: FeaturesRoute,
  HowItWorksRoute: HowItWorksRoute,
  HowToLearnAiRoute: HowToLearnAiRoute,
  LearnAiRoute: LearnAiRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  DomainsSlugRoute: DomainsSlugRoute,
  GlossarySlugRoute: GlossarySlugRoute,
  LibrarySlugRoute: LibrarySlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  GlossaryIndexRoute: GlossaryIndexRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  ApiPublicLlmsRoute: ApiPublicLlmsRoute,
  ApiPublicRobotsRoute: ApiPublicRobotsRoute,
  ApiPublicSitemapRoute: ApiPublicSitemapRoute,
  ApiPublicStatsRoute: ApiPublicStatsRoute,
  ApiPublicHooksAutoGenerateContentRoute:
    ApiPublicHooksAutoGenerateContentRoute,
  ApiPublicHooksTriggerCronRoute: ApiPublicHooksTriggerCronRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
